FROM alpine:3.9 AS build

WORKDIR /opt/app

RUN apk add --no-cache python3 python3-dev py3-pip libffi libffi-dev musl-dev gcc
RUN pip3 install pipenv
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH" VIRTUAL_ENV="/opt/venv"
COPY Pipfile Pipfile.lock /opt/app/
RUN pipenv install --deploy

FROM alpine:3.9
WORKDIR /opt/app
RUN apk add --no-cache python3 libffi
COPY --from=build /opt/venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH" VIRTUAL_ENV="/opt/venv"
COPY . /opt/app/