# Generated by Django 3.0.6 on 2020-05-05 08:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('hook_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'db_table': 'accounts',
            },
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='hook_url',
        ),
        migrations.AddField(
            model_name='wallet',
            name='type',
            field=models.CharField(choices=[('real', 'Real'), ('virtual', 'Virtual')], db_index=True, default='real', max_length=8),
            preserve_default=False,
        ),
    ]
