# Generated by Django 3.0.6 on 2020-05-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200510_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='canceled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='canceled_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='canceled_by',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='canceled_reason',
            field=models.TextField(null=True),
        ),
    ]
