# Generated by Django 3.0.6 on 2020-05-05 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200505_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='account',
            field=models.ForeignKey(default='24d93d44-ec55-41e6-b818-90650605065c', on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to='app.Account'),
            preserve_default=False,
        ),
    ]
